config/routes.rb
Picbag::Application.routes.draw do

  resources :albums do
    resources :photos do
      resources :tags
     end
  end

  devise_for :users

end

app/models/album.rb
class Album
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, :type => String
  belongs_to :user
  has_many :photos
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, :type => String
  field :category, :type => String

  scope :nature, where(:category => 'nature')
  mount_uploader :image, ImageUploader

  belongs_to :album
  embeds_many :tags


end

app/models/tag.rb
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps

  field :x_cord, :type => String
  field :y_cord, :type => String
  field :name, :type => String

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  field :email , :type => String
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :email, :case_sensitive => false
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :albums

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

def new
@album = Album.find(params[:album_id])
@photo = @album.photos.new
end

def create
@album = Album.find(params[:album_id])
@photo = @album.photos.new(params[:photo])
@photo.save
@album.save
redirect_to @album
end

def show
@album = Album.find(params[:album_id])
@photo = @album.photos.find(params[:id])
@tag = @photo.tags.new
end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

     def new

     end

    def create
      @album = Album.find(params[:album_id])
      @photo = @album.photos.find(params[:photo_id])
      @photo.tags.build(params[:tag])
      if @photo.save
      @msg = "created"
      else
        @msg = "There were some error ! Plz try again "
      end
     respond_to do |format|
     format.js
     end
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% if @albums.length > 0 %>
<% @albums.each do |album| %>
  <tr>
    <td><%= album.title %></td>
    <td><%= album.user.email %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @album.title %>
</p>

<p>
  <b>User:</b>
  <%= @album.user.email %>
</p>
<h2>Photos</h2>
<% for photo in @album.photos %>
 <a href="<%=photo.image.url%>"><%= image_tag photo.image.url(:thumb) %></a> | <%=photo.category %>
 <%=link_to "view" ,album_photo_path(@album, photo) %>
<hr />
<% end %>
<%=link_to 'add photo' ,new_album_photo_path(@album) %>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
<%= link_to "Log Out", destroy_user_session_path, :method=>:delete %>
<% else %>
<%= link_to "Log In", user_session_path %>
<% end %>
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
        <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>
    

    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
    <%=render "layouts/nav" %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/new.html.erb
<%= form_for @album.photos.new, :url => album_photos_path,:html => { :multipart => true } do |f| %>
<% if @photo.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

  <ul>
    <% @photo.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :image %><br />
  <%= f.file_field :image %>
</div>
<div class="field">
  <%= f.label :category %>
  <%= f.select "category", [["nature","nature"],["place","place"]] %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/photos/show.html.erb
<h2><%=@photo.title+" from "+ @album.title %></h2>
<% tags = @photo.tags %>

<div id="imgtag">
<% i = 0 %>
<% for t in tags %>
<div class="tagview" id="<%='view_'+i.to_s%>" style="left: <%=t.x_cord%>px; top:<%=t.y_cord%>px"></div>
<% i+=1 %>
<% end %>
<%= image_tag @photo.image.url,:id=>"myimg" %> | <%=@photo.category %>
<div id="tagit" style="display:none">
<div class="box"></div>
<div class="name">
<div class="text">Type any name or tag</div>
<%= form_for @tag ,:url=>album_photo_tags_path(@album, @photo) , :remote=>true do |f| %>
<%=f.text_field(:name, :id=>"tagname") %>
<input type ="submit" value= "Save Tag" id ="btnsave" />
<input type="button" value= "Cancel" id="btncancel" />
<% end %>
</div>
</div>
</div>
<div id="taglist">
 <span class="tagtitle">List of Tags : <%= @photo.tags.length %> Tags </span>
 <ol>
 <% j= 0 %>
 <% tags.each do |t| %>
 <li rel="<%=j.to_s%>"><a href="#"><%=t.name %></a> (<a href="#" class="remove">Remove</a>) </li>
 <% j+=1 %>
 <% end %>
 </ol>
</div>

app/views/tags/create.js.erb
alert("gotcha <%=@msg %>");